const MONGODB_HOST = process.env.MONGODB_HOST
const MONGODB_URI = process.env.MONGODB_URI
const MONGODB_USER = process.env.MONGODB_USER
const MONGODB_PASS = process.env.MONGODB_PASS
const MONGODB_PORT = process.env.MONGODB_PORT
const MONGODB_NAME = process.env.MONGODB_NAME
const MONGODB_PARAM = process.env.MONGODB_PARAM

// export const MONGODB_QUERY = `${MONGODB_URI}${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_NAME}${MONGODB_PARAM}`
export const MONGODB_QUERY = `${MONGODB_URI}${MONGODB_USER}:${MONGODB_PASS}@${MONGODB_HOST}:${MONGODB_PORT}/${MONGODB_NAME}${MONGODB_PARAM}`
